spring:
  application:
    name: ticket-solution-pipeline

  datasource:
    url: jdbc:postgresql://localhost:5432/pip_test
    username: postgres
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# Git Configuration
git:
  repository-path: C:\Users\ASUS-MSi\Downloads\demo\demo
  remote-url: https://github.com/sheimazb/test-MR.git
  token: ${GITHUB_TOKEN}

# Pipeline Configuration  
pipeline:
  github:
    api-url: https://api.github.com
    owner: sheimazb
    repo: test-MR
